_format_version: "2.1"
_transform: true

services:
  - name: auth-v1
    url: http://supabase-auth:9999/auth/v1
    routes:
      - name: auth-v1-route
        strip_path: true
        paths:
          - /auth/v1
    plugins:
      - name: key-auth
        config:
          hide_credentials: true

  - name: rest-v1
    url: http://supabase-rest:3000/
    routes:
      - name: rest-v1-route
        strip_path: true
        paths:
          - /rest/v1
    plugins:
      - name: key-auth
        config:
          hide_credentials: true

  - name: realtime-v1
    url: http://supabase-realtime:4000/socket
    routes:
      - name: realtime-v1-route
        strip_path: true
        paths:
          - /realtime/v1
    plugins:
      - name: key-auth
        config:
          hide_credentials: true

  - name: storage-v1
    url: http://supabase-storage:5000/
    routes:
      - name: storage-v1-route
        strip_path: true
        paths:
          - /storage/v1
    plugins:
      - name: key-auth
        config:
          hide_credentials: true

consumers:
  - username: anon
    keyauth_credentials:
      - key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlzcyI6InN1cGFiYXNlIiwiaWF0IjoxNzcwMTQwMzUzLCJleHAiOjIwODU1MDAzNTN9.mvAPnoMUsCUyp3qm-c4Xkc0XPgUsZ9BiFFLs_VrU7s8
  - username: service_role
    keyauth_credentials:
      - key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaXNzIjoic3VwYWJhc2UiLCJpYXQiOjE3NzAxNDAzNTMsImV4cCI6MjA4NTUwMDM1M30.9vZiFyek464DmOcx2PBcv53E3L0544OmNdztdaoyqeI
